import { describe, it, expect } from "vitest";
import { TYPEHASHES } from "../src/eip712/typehashes.js";
import { PINNED_TYPEHASHES } from "./fixtures.js";

describe("EIP-712 typehashes parity with contract snapshot", () => {
  it("computes DOMAIN_SEPARATOR_TYPEHASH from canonical preimage", () => {
    expect(TYPEHASHES.DOMAIN_SEPARATOR).toBe(PINNED_TYPEHASHES.DOMAIN_SEPARATOR_TYPEHASH);
  });

  it.each([
    ["ACTION_IDENTITY", PINNED_TYPEHASHES.ACTION_IDENTITY_TYPEHASH],
    ["FRESHNESS", PINNED_TYPEHASHES.FRESHNESS_TYPEHASH],
    ["FEE_CAPS", PINNED_TYPEHASHES.FEE_CAPS_TYPEHASH],
    ["DIGEST_HASHES", PINNED_TYPEHASHES.DIGEST_HASHES_TYPEHASH],
    ["EVIDENCE_SOURCE", PINNED_TYPEHASHES.EVIDENCE_SOURCE_TYPEHASH],
    ["EVIDENCE_BUNDLE", PINNED_TYPEHASHES.EVIDENCE_BUNDLE_TYPEHASH],
    ["SPENDER_LIST", PINNED_TYPEHASHES.SPENDER_LIST_TYPEHASH],
    ["ALLOWANCE_SCHEDULE", PINNED_TYPEHASHES.ALLOWANCE_SCHEDULE_TYPEHASH],
    ["FEE_CAP_HASH", PINNED_TYPEHASHES.FEE_CAP_HASH_TYPEHASH],
    ["FAILURE_CONDITION", PINNED_TYPEHASHES.FAILURE_CONDITION_TYPEHASH],
    ["ARMING_CONTEXT", PINNED_TYPEHASHES.ARMING_CONTEXT_TYPEHASH],
    ["OPEN_BOUNDS", PINNED_TYPEHASHES.OPEN_BOUNDS_TYPEHASH],
    ["REBALANCE_BOUNDS", PINNED_TYPEHASHES.REBALANCE_BOUNDS_TYPEHASH],
    ["EXIT_BOUNDS", PINNED_TYPEHASHES.EXIT_BOUNDS_TYPEHASH],
    ["FORCE_EXIT_BOUNDS", PINNED_TYPEHASHES.FORCE_EXIT_BOUNDS_TYPEHASH],
    ["REVOKE_BOUNDS", PINNED_TYPEHASHES.REVOKE_BOUNDS_TYPEHASH],
    ["AUTOMATION_BOUNDS", PINNED_TYPEHASHES.AUTOMATION_BOUNDS_TYPEHASH],
    ["OPEN", PINNED_TYPEHASHES.OPEN_TYPEHASH],
    ["REBALANCE", PINNED_TYPEHASHES.REBALANCE_TYPEHASH],
    ["EXIT", PINNED_TYPEHASHES.EXIT_TYPEHASH],
    ["FORCE_EXIT", PINNED_TYPEHASHES.FORCE_EXIT_TYPEHASH],
    ["REVOKE", PINNED_TYPEHASHES.REVOKE_TYPEHASH],
    ["AUTOMATION_EXEC", PINNED_TYPEHASHES.AUTOMATION_EXEC_TYPEHASH],
    ["PREIMAGE_PROOF", PINNED_TYPEHASHES.PREIMAGE_PROOF_TYPEHASH],
  ])("matches contract snapshot for %s", (name, pinned) => {
    expect(TYPEHASHES[name as keyof typeof TYPEHASHES]).toBe(pinned);
  });
});
